language: node_js
node_js:
- "16.13.2"

install:
- npm install newman

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- node_modules/.bin/newman run testPostman/DemoBook.postman_collection.json
- node_modules/.bin/newman run testPostman/Local.postman_environment.json
- node_modules/.bin/newman run testPostman/QA.postman_environment.json